# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

sequence = [1,1]
@i, @current_number = 0, 0

while @current_number <= 4000000 do
	@current_number = sequence[@i] + sequence[@i+1]
	sequence << @current_number unless @current_number >= 4000000
	@i += 1
end

puts sequence.reject{ |i| i%2 != 0 }.inject(:+)