# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

require Integer

defmodule ProblemTwo do
  def fibonacci(old, new, accum) when new < 4000000 do
    if Integer.is_even(new) do
      fibonacci(new, old + new, accum + new)
    else
      fibonacci(new, old + new, accum)
    end
  end

  def fibonacci(_, _, accum) do
    IO.puts accum
  end
end

ProblemTwo.fibonacci(0,1,0)

# 0, 1, 1, 2, 3, 5, 8